### ISSUE TITLE
Error with integration

### ISSUE THREAD

**Issue by johnsturgeon** [ryanmac8/HA-Mint-Mobile#21]
**Describe the bug**
Sensors went offline after just a short time, error from log file is below

**To Reproduce**
1. Install 
2. Configure
3. Let it run for a day

**Expected behavior**
I expect it to keep working

**Screenshots**

**Desktop (please complete the following information):**
 - OS: HAOS Raspberry Pi 4

**Additional context**

Log entry:
```
Logger: homeassistant.components.sensor
Source: custom_components/mintmobile/api.py:98 
Integration: Sensor (documentation, issues) 
First occurred: May 14, 2022, 10:48:11 AM (12 occurrences) 
Last logged: May 14, 2022, 10:48:13 AM

mintmobile: Error on device update!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in async_device_update
    await task
  File "/config/custom_components/mintmobile/sensor.py", line 208, in async_update
    data = await self.hass.async_add_executor_job(mm.get_all_data_remaining)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mintmobile/api.py", line 143, in get_all_data_remaining
    self.get_family_members()
  File "/config/custom_components/mintmobile/api.py", line 98, in get_family_members
    response = r.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0
```

**Comment by ryanmac8** [comment]
@johnsturgeon Based on this error, it seems like Mint Mobile isn't returning the data in json correctly, which makes me think they might have been down for maintenance. Is this still occuring?
